[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version= "cancun"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "@ensdomains/=lib/v4-periphery/lib/v4-core/node_modules/@ensdomains/",
  "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
  "forge-gas-snapshot/=lib/v4-periphery/lib/forge-gas-snapshot/src/",
  "hardhat/=lib/v4-periphery/lib/v4-core/node_modules/hardhat/",
  "openzeppelin/=lib/v4-periphery/lib/openzeppelin-contracts/contracts/",
  "solmate/=lib/v4-periphery/lib/solmate/src/",
  "v2-core/=lib/v2-core/contracts/",
  "v2-periphery/=lib/v2-periphery/contracts/",
  "v3-core/=lib/v3-core/",
  "@uniswap/v3-core/=lib/v3-core/",
  "v3-periphery/=lib/v3-periphery/contracts/",
  "v4-core/=lib/v4-periphery/lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
base = "${ALCHEMY_ENDPOINT_BASE}"
mainnet = "${ALCHEMY_ENDPOINT_MAINNET}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET}" }
optimism = { key = "${ETHERSCAN_OPTIMISM}" }
base = { key = "${ETHERSCAN_BASE}" }